# Generated by Django 5.1.4 on 2024-12-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='user_id',
            new_name='user',
        ),
    ]
